num_repeats = 100

[[benchmarks]]
name = "DGEMM"
m-sizes = [10, 20, 30]
n-sizes = [10, 50, 30]
k-sizes = [10, 50, 30]

[[benchmarks]]
name = "DGEMV"
m-sizes = [10, 20, 30]
n-sizes = [10, 20, 30]

[[benchmarks]]
name = "DAXPY"
m-sizes = [10, 20, 30]

[[benchmarks]]
name = "NAIVE"
m-sizes = [10, 20, 30]
n-sizes = [10, 20, 30]
k-sizes = [10, 20, 30]
