src += files(
    'main.f90',
    'benchmark_config.f90',
    'benchmark_types.f90',
    'blas/blas_l1.f90',
    'blas/blas_l2.f90',
    'blas/blas_l3.f90',
    'blas/l1_interfaces.f90',
    'blas/l2_interfaces.f90',
    'blas/l3_interfaces.f90',
    'lapack/lapack_linsolve.f90',
    'lapack/lapack_interfaces.f90',
    'misc/misc.f90',
    'gpu/cuda/cublas.f90',
    'gpu/cuda/cuda_interfaces.f90',
    'gpu/hip/hipblas.f90',
    )